---
- hosts: "{{ target_host }}"
  become: True
  gather_facts: no
  vars: 
    - input_file_name:    "{{ input_file_name }}"
    - input_script_name:  "{{ input_script_name}}" 
    - service_name:       "{{ service_name}}"
  tasks:
    - name: Copy script file
      ansible.builtin.copy:
        src: "{{ source_file }}"            # /var/lib/jenkins/workspace/job-demo/test.rb
        dest: "{{ dest_file}}"              #/home/cloud_user/khoa_remote/blog/test.rb
        force: yes

    - name: Exec rails script
      shell: "cd /home/cloud_user/khoa_remote/blog && /usr/local/rvm/bin/rvm all do bundle exec rails runner ./{{ input_script_name }}"
      register: script_output

    - debug:
        var: script_output.stdout_lines


    