---
- hosts: "{{ target_host }}"
  become: True
  gather_facts: no
  tasks:
    - name: Copy script file
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/job-demo/test.rb           #"{{ source_file }}"                    # 
        dest: "{{ input_path}}/{{input_script_name}}"              #/home/cloud_user/khoa_remote/blog/test.rb
        force: yes

    - name: Copy input file (.csv)
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/job-demo/test.rb         #"{{ source_file }}"                    # 
        dest: "{{ input_path}}/{{input_file_name}}"              #/home/cloud_user/khoa_remote/blog/test.rb
        force: yes

    - name: Exec rails runner {{ input_script_name}}
      shell: "cd {{ input_path}} && /usr/local/rvm/bin/rvm all do bundle exec rails runner ./{{ input_script_name }}"
      register: script_output

    - debug:
        var: script_output.stdout_lines


    