---
- hosts: webservers 
  become: True
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      register: out1
    - debug: var=out1.stdout_lines

    - name: start nginx
      service:
          name: nginx
          state: started
      register: out2
    - debug: var=out2.stdout_lines
 