---
- hosts: webservers
  become: True
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      register: hello

    - debug:
        var: hello.stdout_lines

    - shell: cd /home/cloud_user/khoa_remote/blog && ls -la
      register: shell_result

    - debug:
        var: shell_result.stdout_lines

    - name: start nginx
      service:
          name: nginx
          state: started
      register: out2
    - debug: var=out2.stdout_lines